---
- name: Install Sea Creeper Queen
  hosts:
    orchestrator
  become: true
  become_user: "{{ ansible_user }}"
  vars_prompt:
    - name: namespace
      prompt: Enter kubernetes namespace
      private: no
      default: seacreeper
  tasks:
    - name: Creating namespace {{ namespace }}
      command: kubectl create namespace {{ namespace }}
      ignore_errors: yes
    - name: Copy Kubernets YAML
      copy:
        src: requirements
        dest: /tmp/
#    - name: Create Queen Volume
#      command: kubectl apply --namespace={{ namespace }} -f /tmp/requirements/storage.yml
    - name: Create Queen ConfigMap
      command: kubectl apply --namespace={{ namespace }} -f /tmp/requirements/config-map.yml
    - name: Deploy Queen
      command: kubectl apply --namespace={{ namespace }} -f /tmp/requirements/deployment.yml
    - name: Deploy Queen Loadbalancer
      command: kubectl apply --namespace={{ namespace }} -f /tmp/requirements/service.yml
    - name: Delete kubernetes YAML
      file:
        state: absent
        path: "/tmp/requirements"