---
- name: Deploy pihole
  hosts:
    orchestrator
  tasks:
  - name: Copy Kubernets YAML
    copy:
      src: k8s
      dest: /tmp/
  - name: Creating pihole etc volume directory
    become: true
    become_user: "{{ ansible_user }}"
    file:
      path: /home/zxcv32/pihole/etc
      state: directory
  - name: Creating pihole dnsmasq volume directory
    become: true
    become_user: "{{ ansible_user }}"
    file:
      path: /home/zxcv32/pihole/dnsmasq
      state: directory
  - name: Applying secret
    become: true
    become_user: "{{ ansible_user }}"
    command: kubectl apply -f /tmp/k8s/webpassword-secret.yml
  - name: Applying storage
    become: true
    become_user: "{{ ansible_user }}"
    command: kubectl apply -f /tmp/k8s/storage.yml
  - name: Applying deployment
    become: true
    become_user: "{{ ansible_user }}"
    command: kubectl apply -f /tmp/k8s/deployment.yml
  - name: Deleting Kubernetes YAML
    file:
      state: absent
      path: "/tmp/k8s/"
