---
- name: Create Directory
  hosts:
    orchestrator
  tasks:
- name: Deploy pihole
  hosts:
    orchestrator
  tasks:
  - name: Copy Kubernets YAML
    copy:
      src: k8s
      dest: /tmp/
  - name: Applying secret
    become: true
    become_user: "{{ ansible_user }}"
    command: kubectl apply -f /tmp/k8s/webpassword-secret.yml
  - name: Applying storage
    become: true
    become_user: "{{ ansible_user }}"
    command: kubectl apply -f /tmp/k8s/storage.yml
  - name: Applying deployment
    become: true
    become_user: "{{ ansible_user }}"
    command: kubectl apply -f /tmp/k8s/deployment.yml
  - name: Applying service
    become: true
    become_user: "{{ ansible_user }}"
    command: kubectl apply -f /tmp/k8s/svc.yml
  - name: Deleting Kubernetes YAML
    file:
      state: absent
      path: "/tmp/k8s/"
