---
- name: Deploy pihole
  hosts:
    orchestrator
  tasks:
  - name: Copy Kubernets YAML
    copy:
      src: k8s
      dest: /tmp/
  - name: Applying storage
    become: true
    become_user: "{{ ansible_user }}"
    command: kubectl apply -f /tmp/k8s/storage.yml
