version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.4.4
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - confluent
  kafka:
    image: confluentinc/cp-kafka:5.4.4
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka.home.zxcv32.com:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - confluent

networks:
  confluent:
