---
- name: Pihole pre deploy
  hosts:
    docker
  vars_files:
  - env
  become: true
  become_user: "{{ ansible_user }}"
  tasks:
  - name: Create pihole directory
    file:
      path: "~/{{ directory }}"
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
      mode: 0775
      state: directory
  - name: Copy Docker Compose YAML
    copy:
      src: requirements/docker-compose.yml
      dest: "~/{{ directory }}"
  - name: Pull Docker image before disabling systemd-resolved
    command: docker-compose pull
    args:
      chdir: "~/{{ directory }}"
  - name: Disable and stop systemd-resolved
    become_user: root
    systemd:
      name: systemd-resolved
      enabled: no
      state: stopped
