---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pihole-nfs-etc-volume
  labels:
    directory: etc
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /home/j62k86/samba/OneDrive_r/nfs/pihole/etc
    server: storage.home
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-nfs-etc-claim
spec:
  storageClassName: nfs
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      directory: etc
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pihole-nfs-dnsmasq-volume
  labels:
    directory: dnsmasq.d
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  nfs:
    path: /home/j62k86/samba/OneDrive_r/nfs/pihole/dnsmasq
    server: storage.home
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-nfs-dnsmasq-claim
spec:
  storageClassName: nfs
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  selector:
    matchLabels:
      directory: dnsmasq.d
