---
- name: Install node packages
  hosts:
  - nodes
  vars_files:
  - env
  tasks:
  - name: Copying orchestrator logs to nodes
    copy: src={{ logs }} dest={{ logs }}
  - name: Resetting nodes
    shell: kubeadm reset -f
  - name: Executing join command
    shell: "tail -2 {{ logs }} | $SHELL"
  - name: Deleting orchestrator logs from the nodes
    file:
      path: "{{ logs }}"
      state: absent
