---
- name: Deploy MetalLB
  hosts:
  - orchestrator
  tasks:
  - name: Create MetalLB namespace
    become_user: "{{ ansible_user }}"
    command: kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.12.1/manifests/namespace.yaml
  - name: Deploy MetalLB
    become_user: "{{ ansible_user }}"
    command: kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.12.1/manifests/metallb.yaml
  - name: Create MetalLB Config Map
    become_user: "{{ ansible_user }}"
    shell: kubectl create secret generic -n metallb-system memberlist --from-literal=secretkey="$(openssl rand -base64 128)"
  - name: Copy MetalLB Config YAML
    copy:
      src: k8s
      dest: /tmp/
  - name: Create MetalLB ConfigMap
    become_user: "{{ ansible_user }}"
    command: kubectl apply -f /tmp/k8s/metallb-config.yml
  - name: Delete MetalLB Config YAML
    file:
      state: absent
      path: "/tmp/k8s"
