---
- name: Setup NFS
  hosts:
  - orchestrator
  tasks:
  - name: Copy kubernetes storage YAML
    copy:
      src: k8s
      dest: /tmp/
  - name: Create NFS PV
    become_user: "{{ ansible_user }}"
    command: kubectl apply -f /tmp/k8s/nfs-pv.yml
  - name: Delete kubernetes storage YAML
    file:
      state: absent
      path: "/tmp/k8s"
