---
apiVersion: v1
kind: Service
metadata:
  name: grafana-svc
  labels:
    app: grafana
spec:
  selector:
    app: grafana
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
  type: LoadBalancer
