---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-nfs-var-lib-volume
  labels:
    directory: var-lib
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /home/j62k86/samba/k8s/nfs/grafana/var-lib
    server: storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-nfs-var-lib-pvc
spec:
  storageClassName: nfs
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      directory: var-lib
