---
- name: Install orchestrator packages
  hosts:
    orchestrator
  tasks:
    - name: Install kubeadm
      apt:
        name: kubeadm
        state: latest
    - name: Install kubelet
      apt:
        name: kubelet
        state: latest
    - name: Install kubectl
      apt:
        name: kubectl
        state: latest
    - name: Install kubernetes-cni
      apt:
        name: kubernetes-cni
        state: latest
