---
- name: Install orchestrator packages
  hosts:
    orchestrator
  tasks:
  - name: Pulling orchestration images
    shell: kubeadm config images pull
  - name: Initialze orchestrator
    shell: kubeadm init
    register: output
  - name: Store Logs and cluster joining token
    local_action: copy content={{ output.stdout }} dest=~/orchestrator.log
    sudo: False
