---
- name: Install common packages
  hosts:
    orchestrator
    nodes
  tasks:
    - name: Install docker.io
      apt:
        name: docker.io
        state: latest
    - name: Enable docker
      systemd:
        name: docker
        state: enable
    - name: Start docker
      systemd:
        name: docker
        stat: start
    - name: Install curl
      apt:
        name: curl
        state: latest
    - name: Install apt-transport-https
      apt:
        name: Install apt-transport-https
        state: latest
    - name: Install kubeadm
      apt:
        name: Install kubeadm
        state: latest
    - name: Install kubelet
      apt:
        name: Install kubelet
        state: latest
    - name: Install kubectl
      apt:
        name: Install kubectl
        state: latest
    - name: Install kubernetes-cni
      apt:
        name: Install kubernetes-cni
        state: latest
    - name: Adding k8s GPG key
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present
    - name: Adding k8s PPA
      apt_repository:
        repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
        state: present
