---
- name: Install orchestrator packages
  hosts:
    orchestrator
  tasks:
  - name: Pulling orchestration images
    shell: kubeadm config images pull
  - name: Initialze orchestrator
    shell: kubeadm init
    register: output
  - name: Store Logs and cluster joining token
    local_action: copy content={{ output.stdout }} dest=$HOME/orchestrator.log
    sudo: False
  - name: Creating config
    shell: |
     mkdir -p $HOME/.kube
     sudo cp -f /etc/kubernetes/admin.conf $HOME/.kube/config
     sudo chown $(id -u):$(id -g) $HOME/.kube/config
