---
- name: nginx proxy manager deploy
  hosts:
    docker
  vars_files:
  - env
  become: true
  become_user: "{{ ansible_user }}"
  tasks:
  - name: Deploy stack
    command: docker-compose up -d
    args:
      chdir: "~/{{ directory }}"
  - name: Default user
    ansible.builtin.debug:
      msg:
        - "Default username: admin@example.com"
        - "Default password: changeme"
        - "Default port: 81"

