---
apiVersion: v1
kind: Service
metadata:
  name: influxdb-svc
  labels:
    app: influxdb
spec:
  selector:
    app: influxdb
  ports:
  - port: 8086
    targetPort: influxdb
    protocol: TCP
  type: LoadBalancer
