---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: influxdb-nfs-var-lib-volume
  labels:
    directory: var-lib
spec:
  capacity:
    storage: 48Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /home/j62k86/samba/OneDrive_r/nfs/influxdb/var-lib
    server: storage.home
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-nfs-var-lib-pvc
spec:
  storageClassName: nfs
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 48Gi
  selector:
    matchLabels:
      directory: var-lib
