---
- name: Install Helm
  hosts:
    orchestrator
  tasks:
  - name: Adding helm PGP key
    apt_key:
      url: https://baltocdn.com/helm/signing.asc
      state: present
  - name: Install apt-transport-https
    apt:
      name: apt-transport-https
      state: latest
  - name: Adding Helm repo
    shell: echo "deb https://baltocdn.com/helm/stable/debian/ all main" | tee /etc/apt/sources.list.d/helm-stable-debian.list
  - name: update apt repo cache
    apt: update_cache=yes
  - name: Install latest Helm package
    apt:
      name: helm
      state: latest
