---
apiVersion: v1
kind: Service
metadata:
  name: seacreeper-queen-svc
  labels:
    project: seacreeper
    app: queen
spec:
  selector:
    project: seacreeper
    app: queen
  ports:
    - port: 80
      targetPort: api
      protocol: TCP
  type: LoadBalancer
