---
- name: Install Grafana
  hosts:
    orchestrator
  become: true
  become_user: "{{ ansible_user }}"
  tasks:
  - name: Copy Kubernets YAML
    copy:
      src: k8s
      dest: /tmp/
  - name: Create Grafana volume
    command: kubectl -n db apply -f /tmp/k8s/storage.yml
  - name: Deploy Grafana
    command: kubectl -n db apply -f /tmp/k8s/deployment.yml
  - name: Deploy Grafana Loadbalancer
    command: kubectl -n db apply -f /tmp/k8s/service.yml
  - name: Delete kubernetes YAML
    file:
      state: absent
      path: "/tmp/k8s"
