---
- name: Install Kafka
  hosts:
    docker
  vars_files:
    - env
  become: true
  become_user: "{{ ansible_user }}"
  tasks:
    - name: Copy Docker Compose YAML
      copy:
        src: requirements
        dest: "{{ directory }}"
    - name:  Deploy Kafka
      command: docker-compose up -d
      args:
        chdir: "{{ directory }}/requirements"
    - name: Delete Docker Compose YAML
      file:
        state: absent
        path: "{{ directory }}/requirements"