version: '3'
services:
  app:
    restart: always
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./config.json:/app/config/production.json
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
  db:
    restart: always
    image: 'jc21/mariadb-aria:latest'
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'  # not used
      MYSQL_DATABASE: 'npm' # same as name in `name` in config.json
      MYSQL_USER: 'npm' # same as name in `user` in config.json
      MYSQL_PASSWORD: 'npm' # same as name in `password` in config.json
    volumes:
      - ./data/mysql:/var/lib/mysql
