---
- name: Install Grafana
  hosts:
    orchestrator
  become: true
  become_user: "{{ ansible_user }}"
  vars_prompt:
    - name: username
      prompt: Enter InfluxDB username
      private: no
    - name: password
      prompt: Enter InfluxDB user password
  tasks:
  - name: Copy Kubernets YAML
    copy:
      src: k8s
      dest: /tmp/
  - name: Create InfluxDB volume
    command: kubectl apply -f /tmp/k8s/storage.yml
  - name: Create InfluxDB authenticated user
    command: "kubectl create secret generic influxdb-creds --from-literal=INFLUXDB_USERNAME={{ username }} --from-literal=INFLUXDB_PASSWORD={{ password }} --from-literal=INFLUXDB_HOST=influxdb"
  - name: Deploy InfluxDB
    command: kubectl apply -f /tmp/k8s/deployment.yml
  - name: Deploy Grafana Loadbalancer
    command: kubectl apply -f /tmp/k8s/service.yml
  - name: Delete kubernetes YAML
    file:
      state: absent
      path: "/tmp/k8s"
